let evaluations = [
  {
    evaluation_id: 1,
    ouvrage_fk: 1,
    user_fk: 3,
    commentaire: "Un roman captivant, impossible à lâcher !",
    note: 5,
  },
  {
    evaluation_id: 2,
    ouvrage_fk: 2,
    user_fk: 1,
    commentaire: "Un peu cliché, mais agréable à lire.",
    note: 3,
  },
  {
    evaluation_id: 3,
    ouvrage_fk: 1,
    user_fk: 7,
    commentaire: "L’histoire est immersive, j’ai adoré.",
    note: 4,
  },
  {
    evaluation_id: 4,
    ouvrage_fk: 4,
    user_fk: 9,
    commentaire: "Un essai intéressant, mais un peu dense.",
    note: 4,
  },
  {
    evaluation_id: 5,
    ouvrage_fk: 5,
    user_fk: 2,
    commentaire: "Un des meilleurs livres de science-fiction que j’ai lus.",
    note: 5,
  },
  {
    evaluation_id: 6,
    ouvrage_fk: 3,
    user_fk: 4,
    commentaire: "Je n’ai pas accroché à l’histoire.",
    note: 2,
  },
  {
    evaluation_id: 7,
    ouvrage_fk: 6,
    user_fk: 5,
    commentaire: "Très bien documenté, lecture enrichissante.",
    note: 4,
  },
  {
    evaluation_id: 8,
    ouvrage_fk: 7,
    user_fk: 6,
    commentaire: "Une intrigue complexe mais passionnante.",
    note: 5,
  },
  {
    evaluation_id: 9,
    ouvrage_fk: 8,
    user_fk: 1,
    commentaire: "Langage trop soutenu pour moi.",
    note: 2,
  },
  {
    evaluation_id: 10,
    ouvrage_fk: 9,
    user_fk: 8,
    commentaire: "Un classique à découvrir absolument.",
    note: 5,
  },
  {
    evaluation_id: 11,
    ouvrage_fk: 10,
    user_fk: 9,
    commentaire: "Trop lent à mon goût.",
    note: 2,
  },
  {
    evaluation_id: 12,
    ouvrage_fk: 11,
    user_fk: 10,
    commentaire: "Des personnages très attachants.",
    note: 4,
  },
  {
    evaluation_id: 13,
    ouvrage_fk: 12,
    user_fk: 11,
    commentaire: "Un récit inspirant et émouvant.",
    note: 5,
  },
  {
    evaluation_id: 14,
    ouvrage_fk: 13,
    user_fk: 3,
    commentaire: "Très moyen, je m’attendais à mieux.",
    note: 3,
  },
  {
    evaluation_id: 15,
    ouvrage_fk: 14,
    user_fk: 7,
    commentaire: "Lecture rapide et plaisante.",
    note: 4,
  },
  {
    evaluation_id: 16,
    ouvrage_fk: 15,
    user_fk: 2,
    commentaire: "L’univers est bien construit, j’ai adoré.",
    note: 5,
  },
  {
    evaluation_id: 17,
    ouvrage_fk: 16,
    user_fk: 4,
    commentaire: "Pas du tout mon style.",
    note: 1,
  },
  {
    evaluation_id: 18,
    ouvrage_fk: 17,
    user_fk: 5,
    commentaire: "Original et percutant.",
    note: 4,
  },
  {
    evaluation_id: 19,
    ouvrage_fk: 18,
    user_fk: 6,
    commentaire: "Excellent du début à la fin.",
    note: 5,
  },
  {
    evaluation_id: 20,
    ouvrage_fk: 5,
    user_fk: 1,
    commentaire: "Un peu répétitif, dommage.",
    note: 3,
  },
  {
    evaluation_id: 21,
    ouvrage_fk: 1,
    user_fk: 8,
    commentaire: "Quelle imagination, bravo !",
    note: 5,
  },
  {
    evaluation_id: 22,
    ouvrage_fk: 2,
    user_fk: 9,
    commentaire: "Je ne l’ai pas terminé, trop confus.",
    note: 2,
  },
  {
    evaluation_id: 23,
    ouvrage_fk: 3,
    user_fk: 10,
    commentaire: "L’auteur m’a totalement surpris.",
    note: 5,
  },
  {
    evaluation_id: 24,
    ouvrage_fk: 4,
    user_fk: 11,
    commentaire: "Très théorique, peu d’exemples concrets.",
    note: 3,
  },
  {
    evaluation_id: 25,
    ouvrage_fk: 6,
    user_fk: 2,
    commentaire: "Un peu long à démarrer, mais bon ensuite.",
    note: 4,
  },
  {
    evaluation_id: 26,
    ouvrage_fk: 7,
    user_fk: 3,
    commentaire: "Belle plume, c’est agréable à lire.",
    note: 4,
  },
  {
    evaluation_id: 27,
    ouvrage_fk: 8,
    user_fk: 4,
    commentaire: "Je l’ai dévoré en une soirée.",
    note: 5,
  },
  {
    evaluation_id: 28,
    ouvrage_fk: 9,
    user_fk: 5,
    commentaire: "Rien de neuf sous le soleil.",
    note: 2,
  },
  {
    evaluation_id: 29,
    ouvrage_fk: 10,
    user_fk: 6,
    commentaire: "Profond et bien écrit.",
    note: 5,
  },
  {
    evaluation_id: 30,
    ouvrage_fk: 11,
    user_fk: 7,
    commentaire: "Trop complexe pour moi.",
    note: 2,
  },
  {
    evaluation_id: 31,
    ouvrage_fk: 12,
    user_fk: 8,
    commentaire: "Un témoignage bouleversant.",
    note: 5,
  },
  {
    evaluation_id: 32,
    ouvrage_fk: 13,
    user_fk: 9,
    commentaire: "Sympathique, mais pas mémorable.",
    note: 3,
  },
  {
    evaluation_id: 33,
    ouvrage_fk: 14,
    user_fk: 10,
    commentaire: "Un bon moment de lecture.",
    note: 4,
  },
  {
    evaluation_id: 34,
    ouvrage_fk: 15,
    user_fk: 11,
    commentaire: "Je m’attendais à plus de suspense.",
    note: 3,
  },
  {
    evaluation_id: 35,
    ouvrage_fk: 16,
    user_fk: 1,
    commentaire: "Trop de longueurs dans le récit.",
    note: 2,
  },
  {
    evaluation_id: 36,
    ouvrage_fk: 17,
    user_fk: 2,
    commentaire: "Une lecture marquante.",
    note: 5,
  },
  {
    evaluation_id: 37,
    ouvrage_fk: 18,
    user_fk: 3,
    commentaire: "Très documenté, j’ai appris beaucoup.",
    note: 4,
  },
  {
    evaluation_id: 38,
    ouvrage_fk: 1,
    user_fk: 4,
    commentaire: "Un style trop simple à mon goût.",
    note: 3,
  },
  {
    evaluation_id: 39,
    ouvrage_fk: 2,
    user_fk: 5,
    commentaire: "Une belle histoire sur la résilience.",
    note: 4,
  },
  {
    evaluation_id: 40,
    ouvrage_fk: 3,
    user_fk: 6,
    commentaire: "Pas convaincu par la fin.",
    note: 2,
  },
  {
    evaluation_id: 41,
    ouvrage_fk: 3,
    user_fk: 1,
    commentaire: "Un livre bâclé rempli d’émotion.",
    note: 2,
  },
  {
    evaluation_id: 42,
    ouvrage_fk: 5,
    user_fk: 2,
    commentaire: "Ce récit confus du début à la fin.",
    note: 4,
  },
  {
    evaluation_id: 43,
    ouvrage_fk: 11,
    user_fk: 4,
    commentaire: "L’ouvrage puissant qui ne m’a pas convaincu.",
    note: 2,
  },
  {
    evaluation_id: 44,
    ouvrage_fk: 15,
    user_fk: 4,
    commentaire: "Cette œuvre magnifique malgré quelques défauts.",
    note: 1,
  },
  {
    evaluation_id: 45,
    ouvrage_fk: 1,
    user_fk: 5,
    commentaire: "Ce texte magnifique malgré quelques défauts.",
    note: 4,
  },
  {
    evaluation_id: 46,
    ouvrage_fk: 5,
    user_fk: 7,
    commentaire: "L’ouvrage ennuyeux qui ne m’a pas convaincu.",
    note: 5,
  },
  {
    evaluation_id: 47,
    ouvrage_fk: 13,
    user_fk: 1,
    commentaire: "L’ouvrage magnifique qui ne m’a pas convaincu.",
    note: 4,
  },
  {
    evaluation_id: 48,
    ouvrage_fk: 8,
    user_fk: 3,
    commentaire: "L’ouvrage magnifique qui ne m’a pas convaincu.",
    note: 5,
  },
  {
    evaluation_id: 49,
    ouvrage_fk: 10,
    user_fk: 7,
    commentaire: "Cette œuvre confus malgré quelques défauts.",
    note: 1,
  },
  {
    evaluation_id: 50,
    ouvrage_fk: 10,
    user_fk: 2,
    commentaire: "Ce bouquin magnifique rempli d’émotion.",
    note: 2,
  },
  {
    evaluation_id: 51,
    ouvrage_fk: 12,
    user_fk: 9,
    commentaire: "L’ouvrage ennuyeux qui sort du lot.",
    note: 1,
  },
  {
    evaluation_id: 52,
    ouvrage_fk: 6,
    user_fk: 10,
    commentaire: "L’ouvrage moyen malgré quelques défauts.",
    note: 3,
  },
  {
    evaluation_id: 53,
    ouvrage_fk: 14,
    user_fk: 11,
    commentaire: "Ce texte touchant du début à la fin.",
    note: 5,
  },
  {
    evaluation_id: 54,
    ouvrage_fk: 17,
    user_fk: 4,
    commentaire: "Ce bouquin puissant malgré quelques défauts.",
    note: 4,
  },
  {
    evaluation_id: 55,
    ouvrage_fk: 9,
    user_fk: 6,
    commentaire: "Cette œuvre déroutant qui ne m’a pas convaincu.",
    note: 2,
  },
  {
    evaluation_id: 56,
    ouvrage_fk: 7,
    user_fk: 3,
    commentaire: "Ce bouquin inspirant malgré quelques défauts.",
    note: 4,
  },
  {
    evaluation_id: 57,
    ouvrage_fk: 2,
    user_fk: 2,
    commentaire: "Un livre superficiel rempli d’émotion.",
    note: 2,
  },
  {
    evaluation_id: 58,
    ouvrage_fk: 4,
    user_fk: 8,
    commentaire: "L’ouvrage confus du début à la fin.",
    note: 3,
  },
  {
    evaluation_id: 59,
    ouvrage_fk: 16,
    user_fk: 1,
    commentaire: "Cette œuvre moyen qui sort du lot.",
    note: 4,
  },
  {
    evaluation_id: 60,
    ouvrage_fk: 18,
    user_fk: 5,
    commentaire: "Un livre brillant qui m’a marqué profondément.",
    note: 5,
  },
  {
    evaluation_id: 61,
    ouvrage_fk: 3,
    user_fk: 11,
    commentaire: "Un livre superficiel comme on en lit rarement.",
    note: 3,
  },
  {
    evaluation_id: 62,
    ouvrage_fk: 1,
    user_fk: 7,
    commentaire: "Ce bouquin puissant à lire absolument.",
    note: 4,
  },
  {
    evaluation_id: 63,
    ouvrage_fk: 15,
    user_fk: 11,
    commentaire: "Cette œuvre captivant à lire absolument.",
    note: 3,
  },
  {
    evaluation_id: 64,
    ouvrage_fk: 15,
    user_fk: 9,
    commentaire: "Cette histoire inspirant rempli d’émotion.",
    note: 5,
  },
  {
    evaluation_id: 65,
    ouvrage_fk: 17,
    user_fk: 1,
    commentaire: "Un livre superficiel rempli d’émotion.",
    note: 2,
  },
  {
    evaluation_id: 66,
    ouvrage_fk: 9,
    user_fk: 10,
    commentaire: "Cette histoire inspirant avec trop de longueurs.",
    note: 4,
  },
  {
    evaluation_id: 67,
    ouvrage_fk: 13,
    user_fk: 11,
    commentaire: "Cette histoire touchant malgré quelques défauts.",
    note: 3,
  },
  {
    evaluation_id: 68,
    ouvrage_fk: 5,
    user_fk: 11,
    commentaire: "Ce roman touchant qui m’a marqué profondément.",
    note: 3,
  },
  {
    evaluation_id: 69,
    ouvrage_fk: 15,
    user_fk: 8,
    commentaire: "Cette histoire confus comme on en lit rarement.",
    note: 2,
  },
  {
    evaluation_id: 70,
    ouvrage_fk: 8,
    user_fk: 7,
    commentaire: "Ce roman déroutant avec trop de longueurs.",
    note: 3,
  },
  {
    evaluation_id: 71,
    ouvrage_fk: 18,
    user_fk: 6,
    commentaire: "Ce roman brillant avec trop de longueurs.",
    note: 2,
  },
  {
    evaluation_id: 72,
    ouvrage_fk: 13,
    user_fk: 5,
    commentaire: "Un livre ennuyeux comme on en lit rarement.",
    note: 4,
  },
  {
    evaluation_id: 73,
    ouvrage_fk: 16,
    user_fk: 11,
    commentaire: "Cette œuvre déroutant qui ne m’a pas convaincu.",
    note: 2,
  },
  {
    evaluation_id: 74,
    ouvrage_fk: 5,
    user_fk: 11,
    commentaire: "Ce roman superficiel avec trop de longueurs.",
    note: 3,
  },
  {
    evaluation_id: 75,
    ouvrage_fk: 16,
    user_fk: 1,
    commentaire: "Un livre déroutant qui m’a marqué profondément.",
    note: 1,
  },
  {
    evaluation_id: 76,
    ouvrage_fk: 2,
    user_fk: 7,
    commentaire: "Ce bouquin puissant à éviter selon moi.",
    note: 4,
  },
  {
    evaluation_id: 77,
    ouvrage_fk: 8,
    user_fk: 11,
    commentaire: "Ce récit moyen du début à la fin.",
    note: 2,
  },
  {
    evaluation_id: 78,
    ouvrage_fk: 14,
    user_fk: 3,
    commentaire: "Cette histoire superficiel à éviter selon moi.",
    note: 2,
  },
  {
    evaluation_id: 79,
    ouvrage_fk: 5,
    user_fk: 1,
    commentaire: "Ce texte puissant comme on en lit rarement.",
    note: 2,
  },
  {
    evaluation_id: 80,
    ouvrage_fk: 6,
    user_fk: 5,
    commentaire: "Ce texte bâclé qui m’a marqué profondément.",
    note: 2,
  },
  {
    evaluation_id: 81,
    ouvrage_fk: 8,
    user_fk: 8,
    commentaire: "Cette histoire magnifique à éviter selon moi.",
    note: 2,
  },
  {
    evaluation_id: 82,
    ouvrage_fk: 5,
    user_fk: 4,
    commentaire: "Ce texte superficiel comme on en lit rarement.",
    note: 3,
  },
  {
    evaluation_id: 83,
    ouvrage_fk: 15,
    user_fk: 11,
    commentaire: "Cette œuvre touchant malgré quelques défauts.",
    note: 3,
  },
  {
    evaluation_id: 84,
    ouvrage_fk: 1,
    user_fk: 9,
    commentaire: "Ce roman confus à éviter selon moi.",
    note: 5,
  },
  {
    evaluation_id: 85,
    ouvrage_fk: 13,
    user_fk: 6,
    commentaire: "Cette œuvre captivant qui sort du lot.",
    note: 4,
  },
  {
    evaluation_id: 86,
    ouvrage_fk: 8,
    user_fk: 10,
    commentaire: "Ce roman ennuyeux qui m’a marqué profondément.",
    note: 3,
  },
  {
    evaluation_id: 87,
    ouvrage_fk: 5,
    user_fk: 6,
    commentaire: "Ce roman bâclé à éviter selon moi.",
    note: 1,
  },
  {
    evaluation_id: 88,
    ouvrage_fk: 11,
    user_fk: 11,
    commentaire: "Ce récit magnifique qui ne m’a pas convaincu.",
    note: 5,
  },
  {
    evaluation_id: 89,
    ouvrage_fk: 8,
    user_fk: 8,
    commentaire: "Cette histoire ennuyeux comme on en lit rarement.",
    note: 3,
  },
  {
    evaluation_id: 90,
    ouvrage_fk: 9,
    user_fk: 10,
    commentaire: "Un livre touchant comme on en lit rarement.",
    note: 3,
  },
];

export { evaluations };
